import type { Product } from '../types/admin';
import type {
  StaffUser,
  AuditLog,
  AdminNotification,
  DiscountRule,
  CategoryItem,
  ReviewItem,
  DeliveryZone,
  CustomerProfile,
  AdminOrder,
  InventoryLogItem,
  CMSConfig,
  StoreSettings,
  OrderWorkflowStatus,
  PaymentRecordStatus,
  InventoryAdjustmentReason,
  StaffRole,
} from '../types/admin';
import type { PaymentRecord } from '../types/payment';

// Seed Initial Products
const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'FUR-LIV-001',
    name: 'Sapphire Velvet Accent Chair',
    subtitle: 'Sculptural luxury barrel armchair with tapered solid wood legs',
    category: 'Armchairs & Seating',
    room: 'living',
    price: 299,
    originalPrice: 349,
    discountPercent: 14,
    rating: 5,
    reviewsCount: 142,
    image: '/hero-chair.jpg',
    galleryImages: [
      '/hero-chair.jpg',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Impeccably tailored in rich royal velvet, this accent chair provides high-density foam cushioning with a timeless silhouette and gold-finished steel base.',
    longDescription: 'Crafted with premium Italian-imported velvet fabric, high-resilience foam core, and solid kiln-dried hardwood interior framing. Its ergonomic contour supports ideal posture while delivering an editorial centerpiece for modern living rooms or private lounges.',
    dimensions: { width: '32 in (81 cm)', depth: '31 in (79 cm)', height: '34 in (86 cm)', unit: 'imperial' },
    materials: ['Royal Velvet Upholstery', 'Kiln-Dried Hardwood Frame', 'Brushed Brass Steel Legs', 'High-Density Memory Foam'],
    colors: [
      { name: 'Royal Plum', hex: '#4A1E6D', threeColor: 0x4a1e6d },
      { name: 'Emerald Velvet', hex: '#1B4332', threeColor: 0x1b4332 },
      { name: 'Warm Cream', hex: '#EAE4D9', threeColor: 0xeae4d9 },
      { name: 'Charcoal Obsidian', hex: '#212529', threeColor: 0x212529 },
    ],
    inStock: true,
    stockCount: 14,
    isBestSeller: true,
    threeModelType: 'chair',
  },
  {
    id: 'prod-2',
    sku: 'FUR-LIV-002',
    name: 'Modern Coffee Table',
    subtitle: 'Dual-tiered dark walnut table with matte black steel frame',
    category: 'Tables & Consoles',
    room: 'living',
    price: 199,
    originalPrice: 229,
    discountPercent: 13,
    rating: 5,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'A striking oval coffee table featuring genuine walnut veneer and an integrated lower magazine shelf supported by a low-profile architectural frame.',
    longDescription: 'Designed with minimalist proportion in mind. The heat and scratch-resistant lacquer coating ensures long-lasting durability against coffee rings and daily use.',
    dimensions: { width: '48 in (122 cm)', depth: '24 in (61 cm)', height: '18 in (46 cm)', unit: 'imperial' },
    materials: ['FSC-Certified American Walnut', 'Powder-Coated Carbon Steel', 'Anti-Scratch Satin Finish'],
    colors: [
      { name: 'Smoked Walnut', hex: '#3E2723', threeColor: 0x3e2723 },
      { name: 'Natural White Oak', hex: '#D7C4A5', threeColor: 0xd7c4a5 },
      { name: 'Ebony Black', hex: '#1C1917', threeColor: 0x1c1917 },
    ],
    inStock: true,
    stockCount: 22,
    threeModelType: 'table',
  },
  {
    id: 'prod-3',
    sku: 'FUR-BED-003',
    name: 'Upholstered Bed Frame',
    subtitle: 'Platform bed with padded vertical channel tufting',
    category: 'Beds & Headboards',
    room: 'bedroom',
    price: 699,
    originalPrice: 799,
    discountPercent: 12,
    rating: 5,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef0?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Solid engineered slat support system eliminates the need for a box spring while the deep padded headboard provides plush support for reading in bed.',
    longDescription: 'Featuring acoustic-dampened slat rails that ensure noiseless rest. Available in heavy linen blend and velvet finishes with tapered wooden corner posts.',
    dimensions: { width: '66 in (168 cm)', depth: '86 in (218 cm)', height: '48 in (122 cm)', unit: 'imperial' },
    materials: ['Heavy Belgian Linen Blend', 'Reinforced Solid Pine Slats', 'Cold-Rolled Steel Center Beam'],
    colors: [
      { name: 'Heather Charcoal', hex: '#374151', threeColor: 0x374151 },
      { name: 'Oatmeal Beige', hex: '#E5DCC5', threeColor: 0xe5dcc5 },
      { name: 'Imperial Violet', hex: '#3B184F', threeColor: 0x3b184f },
    ],
    inStock: true,
    stockCount: 8,
    isNew: true,
    threeModelType: 'bed',
  },
  {
    id: 'prod-4',
    sku: 'FUR-STO-004',
    name: 'Wooden Sideboard',
    subtitle: 'Mid-century modern credenza with fluted tambour doors',
    category: 'Credenzas & Buffets',
    room: 'storage',
    price: 399,
    originalPrice: 499,
    discountPercent: 20,
    badge: '-20%',
    rating: 5,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'A spacious multi-compartment storage console featuring softly sliding tambour doors, adjustable shelving, and integrated cable routing for media devices.',
    longDescription: 'Hand-assembled by master cabinetmakers with subtle brass door hardware and durable soft-close hinges.',
    dimensions: { width: '60 in (152 cm)', depth: '18 in (46 cm)', height: '30 in (76 cm)', unit: 'imperial' },
    materials: ['Solid European Ash & Walnut Veneer', 'Brushed Brass Knobs', 'Soft-Close Concealed Hinges'],
    colors: [
      { name: 'Natural Ash', hex: '#CDB194', threeColor: 0xcdb194 },
      { name: 'Dark Oak', hex: '#4A3728', threeColor: 0x4a3728 },
    ],
    inStock: true,
    stockCount: 11,
    threeModelType: 'sideboard',
  },
  {
    id: 'prod-5',
    sku: 'FUR-OFF-005',
    name: 'Ergonomic Office Chair',
    subtitle: 'Dynamic lumbar-adaptive task chair with 4D armrests',
    category: 'Executive & Task Seating',
    room: 'office',
    price: 249,
    originalPrice: 289,
    discountPercent: 14,
    rating: 5,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1580481077197-285b0cb046b4?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1580481077197-285b0cb046b4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Engineered for 12+ hours of continuous comfort with breathable elastomeric mesh, multi-angle tilt lock, and pneumatic seat height adjustment.',
    longDescription: 'BIFMA certified for commercial and home executive use. Smooth rollerblade casters glide safely over hardwood and rugs alike without scratching.',
    dimensions: { width: '26 in (66 cm)', depth: '26 in (66 cm)', height: '42-46 in (107-117 cm)', unit: 'imperial' },
    materials: ['Elastomeric Breathable Mesh', 'Die-Cast Aluminum Base', 'Polyurethane Silent Casters'],
    colors: [
      { name: 'Executive Slate', hex: '#4B5563', threeColor: 0x4b5563 },
      { name: 'Midnight Jet', hex: '#111827', threeColor: 0x111827 },
      { name: 'Alabaster Silver', hex: '#9CA3AF', threeColor: 0x9ca3af },
    ],
    inStock: true,
    stockCount: 35,
    threeModelType: 'chair',
  },
  {
    id: 'prod-6',
    sku: 'FUR-OFF-006',
    name: 'Writing Desk',
    subtitle: 'Solid oak workstation with concealed drawer & brass details',
    category: 'Workstations & Desks',
    room: 'office',
    price: 254,
    originalPrice: 299,
    discountPercent: 15,
    badge: '-15%',
    rating: 5,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Clean Scandinavian lines with an integrated felt-lined drawer for laptop storage and subtle magnetic cord organization.',
    longDescription: 'Made of sustainably harvested American White Oak with solid joinery and angled legs that provide maximum legroom and visual lightness.',
    dimensions: { width: '47 in (120 cm)', depth: '22 in (56 cm)', height: '29.5 in (75 cm)', unit: 'imperial' },
    materials: ['Solid White Oak', 'Felt Drawer Liner', 'Brass Cable Grommet'],
    colors: [
      { name: 'Natural Oak', hex: '#D2B48C', threeColor: 0xd2b48c },
      { name: 'Smoked Chestnut', hex: '#5D4037', threeColor: 0x5d4037 },
    ],
    inStock: true,
    stockCount: 19,
    threeModelType: 'desk',
  },
  {
    id: 'prod-7',
    sku: 'FUR-LIV-007',
    name: 'Modular Velvet Sectional Sofa',
    subtitle: 'This Week Highlight: Deep tufted L-shape luxury sofa',
    category: 'Sofas & Sectionals',
    room: 'living',
    price: 1499,
    originalPrice: 1799,
    discountPercent: 17,
    badge: 'NEW',
    rating: 5,
    reviewsCount: 382,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Our flagship modular sofa upholstered in royal plum velvet with deep seat cushions, feather-down blend filling, and modular clips for reconfigurable layouts.',
    longDescription: 'Featured in this weeks highlights. Includes 4 matching velvet throw pillows and precision-turned solid metal feet.',
    dimensions: { width: '112 in (284 cm)', depth: '68 in (173 cm)', height: '33 in (84 cm)', unit: 'imperial' },
    materials: ['Italian Heavy Velvet', 'Down-Feather Wrapped Pocket Springs', 'Solid Beechwood Internal Frame'],
    colors: [
      { name: 'Signature Plum', hex: '#3B184F', threeColor: 0x3b184f },
      { name: 'Deep Amethyst', hex: '#5A189A', threeColor: 0x5a189a },
      { name: 'Champagne Beige', hex: '#E6D5C3', threeColor: 0xe6d5c3 },
      { name: 'Forest Green', hex: '#1E3F20', threeColor: 0x1e3f20 },
    ],
    inStock: true,
    stockCount: 7,
    isFeatured: true,
    isNew: true,
    threeModelType: 'sofa',
  },
  {
    id: 'prod-8',
    sku: 'FUR-DIN-008',
    name: 'Sculptural Round Dining Set',
    subtitle: 'Circular dining table with 4 velvet wrapped tub chairs',
    category: 'Dining Sets',
    room: 'dining',
    price: 899,
    originalPrice: 1199,
    discountPercent: 25,
    badge: '-25%',
    rating: 5,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'A grand circular pedestal dining table in dark walnut with 4 ergonomic dining chairs upholstered in matching amethyst velvet.',
    longDescription: 'Pedestal base ensures unobstructed seating. Treated with stain-resistant coating to safeguard against wine or sauce spills during festive dinners.',
    dimensions: { width: '48 in Dia (122 cm)', depth: '48 in (122 cm)', height: '30 in (76 cm)', unit: 'imperial' },
    materials: ['American Walnut', 'Curved Plywood Shell', 'Commercial Grade Velvet'],
    colors: [
      { name: 'Dark Plum & Walnut', hex: '#4A1E6D', threeColor: 0x4a1e6d },
      { name: 'Ivory & Natural Ash', hex: '#F0ECE1', threeColor: 0xf0ece1 },
    ],
    inStock: true,
    stockCount: 9,
    isBestSeller: true,
    isDealOfTheWeek: true,
    threeModelType: 'table',
  },
  {
    id: 'prod-9',
    sku: 'FUR-LIV-009',
    name: 'Plum Velvet Lounge Chair',
    subtitle: 'Deal of the week: Deep contoured barrel chair',
    category: 'Armchairs & Seating',
    room: 'living',
    price: 225,
    originalPrice: 300,
    discountPercent: 25,
    badge: '-25%',
    rating: 5,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'A cozy barrel-back lounge chair with 360-degree silent swivel mechanism and luxurious deep plum upholstery.',
    longDescription: 'Soft channel pleating adds visual texture, pairing effortlessly with minimalist or maximalist interiors.',
    dimensions: { width: '30 in (76 cm)', depth: '30 in (76 cm)', height: '31 in (79 cm)', unit: 'imperial' },
    materials: ['Silky Velvet', 'Silent Steel Swivel Plate', 'Molded High-Density Foam'],
    colors: [
      { name: 'Royal Plum', hex: '#4A1E6D', threeColor: 0x4a1e6d },
      { name: 'Blush Rose', hex: '#C98B96', threeColor: 0xc98b96 },
    ],
    inStock: true,
    stockCount: 16,
    isDealOfTheWeek: true,
    threeModelType: 'chair',
  },
  {
    id: 'prod-10',
    sku: 'FUR-STO-010',
    name: 'Minimalist Open Bookshelf',
    subtitle: '6-tier staggered architectural shelving unit',
    category: 'Shelves & Bookcases',
    room: 'storage',
    price: 320,
    originalPrice: 400,
    discountPercent: 20,
    badge: '-20%',
    rating: 5,
    reviewsCount: 53,
    image: 'https://images.unsplash.com/photo-1594040226829-7f251ab46d80?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1594040226829-7f251ab46d80?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'An open geometric display shelf perfect for art objects, collectibles, books, and indoor plants. Includes wall anchoring hardware.',
    longDescription: 'Solid timber frame with reinforced cross-bracing and non-marring adjustable leveling feet.',
    dimensions: { width: '38 in (96 cm)', depth: '14 in (35 cm)', height: '74 in (188 cm)', unit: 'imperial' },
    materials: ['Solid Oak Uprights', 'Veneered Shelves', 'Steel Anti-Tip Hardware'],
    colors: [
      { name: 'Honey Oak', hex: '#B8860B', threeColor: 0xb8860b },
      { name: 'Smoked Walnut', hex: '#4A3728', threeColor: 0x4a3728 },
    ],
    inStock: true,
    stockCount: 12,
    isDealOfTheWeek: true,
    threeModelType: 'shelf',
  },
  {
    id: 'prod-11',
    sku: 'FUR-LIV-011',
    name: 'Velvet Ottoman Pouf',
    subtitle: 'Round footrest & extra seating with gold plinth',
    category: 'Ottomans & Benches',
    room: 'living',
    price: 135,
    originalPrice: 150,
    discountPercent: 10,
    badge: '-10%',
    rating: 5,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Versatile, lightweight, and lavish. Use as a footrest, vanity seat, or impromptu coffee table when paired with a serving tray.',
    longDescription: 'Padded with memory foam topper over solid cylinder core. Gold stainless steel base provides a glamorous metallic kick.',
    dimensions: { width: '18 in Dia (45 cm)', depth: '18 in (45 cm)', height: '17 in (43 cm)', unit: 'imperial' },
    materials: ['Velvet Fabric', 'High-Density Foam Core', 'Polished Brass Base Ring'],
    colors: [
      { name: 'Plum Violet', hex: '#5A189A', threeColor: 0x5a189a },
      { name: 'Teal Peacock', hex: '#005F73', threeColor: 0x005f73 },
    ],
    inStock: true,
    stockCount: 25,
    isDealOfTheWeek: true,
    threeModelType: 'chair',
  },
  {
    id: 'prod-12',
    sku: 'FUR-OUT-012',
    name: 'Teak Outdoor Lounge Set',
    subtitle: 'All-weather teak twin club chairs with Sunbrella cushions',
    category: 'Patio & Outdoor',
    room: 'outdoor',
    price: 1250,
    originalPrice: 1450,
    discountPercent: 14,
    badge: 'LUXURY',
    rating: 5,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Grade-A natural teak harvested sustainably from certified plantations. Weatherproof UV and water-repellent Sunbrella cushions in stone beige.',
    longDescription: 'Teak naturally weathers to a distinguished silver-gray patina or can be oiled annually to retain its rich honey color.',
    dimensions: { width: '34 in (86 cm)', depth: '36 in (91 cm)', height: '30 in (76 cm)', unit: 'imperial' },
    materials: ['Grade-A Plantation Teak', 'Sunbrella Outdoor Fabric', 'Quick-Dry Reticulated Foam'],
    colors: [
      { name: 'Natural Teak & Stone', hex: '#C2A379', threeColor: 0xc2a379 },
    ],
    inStock: true,
    stockCount: 6,
    threeModelType: 'chair',
  },
];

// Seed Categories
const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-1',
    name: 'Living Room',
    slug: 'living-room',
    description: 'Curated seating, sculptural sectionals, and bespoke coffee tables.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    roomKey: 'living',
    displayOrder: 1,
    active: true,
    seoTitle: 'Luxury Living Room Furniture | FURNITURA',
    seoDescription: 'Discover our exclusive collection of velvet sectionals, lounge chairs, and consoles.',
    productCount: 5,
  },
  {
    id: 'cat-2',
    name: 'Bedroom',
    slug: 'bedroom',
    description: 'Upholstered platform beds, nightstands, and artisanal lighting.',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    roomKey: 'bedroom',
    displayOrder: 2,
    active: true,
    seoTitle: 'Luxury Bedroom Sets & Platform Beds | FURNITURA',
    seoDescription: 'Transform your bedroom into a restful sanctuary with channel tufted beds.',
    productCount: 1,
  },
  {
    id: 'cat-3',
    name: 'Dining Room',
    slug: 'dining-room',
    description: 'Sculptural dining tables, curved tub chairs, and statement credenzas.',
    image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
    roomKey: 'dining',
    displayOrder: 3,
    active: true,
    seoTitle: 'Contemporary Dining Room Furniture | FURNITURA',
    seoDescription: 'Host in style with solid walnut circular tables and velvet dining chairs.',
    productCount: 1,
  },
  {
    id: 'cat-4',
    name: 'Office & Study',
    slug: 'office',
    description: 'Ergonomic task seating, minimalist oak desks, and executive organization.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
    roomKey: 'office',
    displayOrder: 4,
    active: true,
    seoTitle: 'Executive Office Furniture & Desks | FURNITURA',
    seoDescription: 'Elevate your workspace with ergonomic luxury seating and solid oak workstations.',
    productCount: 2,
  },
  {
    id: 'cat-5',
    name: 'Storage & Display',
    slug: 'storage',
    description: 'Fluted credenzas, modular bookshelves, and refined sideboards.',
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
    roomKey: 'storage',
    displayOrder: 5,
    active: true,
    seoTitle: 'Designer Storage Credenzas & Shelving | FURNITURA',
    seoDescription: 'Fluted tambour door sideboards and architectural open display shelving.',
    productCount: 2,
  },
  {
    id: 'cat-6',
    name: 'Outdoor & Patio',
    slug: 'outdoor',
    description: 'Grade-A teak outdoor lounges, Sunbrella upholstery, and weather-resistant sets.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    roomKey: 'outdoor',
    displayOrder: 6,
    active: true,
    seoTitle: 'All-Weather Luxury Teak Outdoor Furniture | FURNITURA',
    seoDescription: 'Sustainably harvested teak and weather-resistant Sunbrella cushions.',
    productCount: 1,
  },
];

// Seed Discounts
const INITIAL_DISCOUNTS: DiscountRule[] = [
  {
    id: 'disc-1',
    name: 'FURNITURA Grand Welcome',
    code: 'FURNITURA10',
    type: 'percentage',
    value: 10,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    minOrderValue: 200,
    maxDiscount: 150,
    usageLimit: 500,
    perCustomerLimit: 1,
    usageCount: 142,
    status: 'ACTIVE',
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'disc-2',
    name: 'VIP Autumn Luxury 20%',
    code: 'LUXURY20',
    type: 'percentage',
    value: 20,
    startDate: '2026-09-01T00:00:00.000Z',
    endDate: '2026-10-31T23:59:59.000Z',
    minOrderValue: 500,
    maxDiscount: 400,
    usageLimit: 100,
    perCustomerLimit: 1,
    usageCount: 38,
    status: 'ACTIVE',
    createdAt: '2026-09-01T09:00:00.000Z',
    updatedAt: '2026-09-27T12:00:00.000Z',
  },
  {
    id: 'disc-3',
    name: 'First Order Welcome Voucher',
    code: 'WELCOME20',
    type: 'percentage',
    value: 20,
    startDate: '2026-01-01T00:00:00.000Z',
    endDate: '2026-12-31T23:59:59.000Z',
    minOrderValue: 150,
    maxDiscount: 200,
    usageLimit: 1000,
    perCustomerLimit: 1,
    usageCount: 421,
    status: 'ACTIVE',
    createdAt: '2026-01-01T08:00:00.000Z',
    updatedAt: '2026-09-25T11:00:00.000Z',
  },
  {
    id: 'disc-4',
    name: 'VIP Private Salon $100 OFF',
    code: 'VIP100',
    type: 'fixed',
    value: 100,
    startDate: '2026-09-15T00:00:00.000Z',
    endDate: '2026-10-15T23:59:59.000Z',
    minOrderValue: 800,
    usageLimit: 50,
    perCustomerLimit: 1,
    usageCount: 19,
    status: 'ACTIVE',
    createdAt: '2026-09-15T14:00:00.000Z',
    updatedAt: '2026-09-26T16:00:00.000Z',
  },
];

// Seed Delivery Zones
const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone-kigali-urban',
    name: 'Kigali Urban Express',
    region: 'Kigali City',
    districts: ['Nyarugenge', 'Gasabo', 'Kicukiro'],
    fee: 25,
    currency: 'USD',
    estimatedDays: '1-2 business days',
    freeShippingThreshold: 500,
    active: true,
    whiteGloveAvailable: true,
    whiteGloveFee: 40,
    description: 'Direct door-to-door white glove delivery within Kigali metropolis.',
  },
  {
    id: 'zone-northern',
    name: 'Northern Province (Musanze & Gicumbi)',
    region: 'Northern Province',
    districts: ['Musanze', 'Gicumbi', 'Rulindo', 'Burera', 'Gakenke'],
    fee: 45,
    currency: 'USD',
    estimatedDays: '2-4 business days',
    freeShippingThreshold: 900,
    active: true,
    whiteGloveAvailable: true,
    whiteGloveFee: 65,
    description: 'Dedicated regional freight transport to northern districts.',
  },
  {
    id: 'zone-eastern',
    name: 'Eastern Province (Bugesera & Rwamagana)',
    region: 'Eastern Province',
    districts: ['Rwamagana', 'Bugesera', 'Kayonza', 'Gatsibo', 'Ngoma', 'Kirehe', 'Nyagatare'],
    fee: 45,
    currency: 'USD',
    estimatedDays: '2-4 business days',
    freeShippingThreshold: 900,
    active: true,
    whiteGloveAvailable: true,
    whiteGloveFee: 65,
    description: 'Weekly scheduled luxury furniture dispatch to eastern regional hubs.',
  },
  {
    id: 'zone-western',
    name: 'Western Province (Rubavu & Karongi)',
    region: 'Western Province',
    districts: ['Rubavu', 'Karongi', 'Rusizi', 'Nyamasheke', 'Rutsiro', 'Ngororero', 'Nyabihu'],
    fee: 55,
    currency: 'USD',
    estimatedDays: '3-5 business days',
    freeShippingThreshold: 1200,
    active: true,
    whiteGloveAvailable: true,
    whiteGloveFee: 75,
    description: 'Secure wrapped transport to western lake-front and highland districts.',
  },
  {
    id: 'zone-southern',
    name: 'Southern Province (Huye & Muhanga)',
    region: 'Southern Province',
    districts: ['Huye', 'Muhanga', 'Nyanza', 'Ruhango', 'Gisagara', 'Nyamagabe', 'Nyaruguru', 'Kamonyi'],
    fee: 45,
    currency: 'USD',
    estimatedDays: '2-4 business days',
    freeShippingThreshold: 900,
    active: true,
    whiteGloveAvailable: true,
    whiteGloveFee: 65,
    description: 'Scheduled freight dispatch to southern cultural & university centers.',
  },
];

// Seed Staff Users
const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'staff-1',
    name: 'Diane Uwase',
    email: 'admin@furnitura.luxury',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'orders:read', 'orders:write',
      'payments:read', 'payments:write',
      'products:read', 'products:write',
      'inventory:read', 'inventory:write',
      'discounts:read', 'discounts:write',
      'customers:read', 'customers:write',
      'categories:read', 'categories:write',
      'reviews:read', 'reviews:write',
      'delivery:read', 'delivery:write',
      'cms:read', 'cms:write',
      '3d:read', '3d:write',
      'analytics:read',
      'notifications:read',
      'staff:read', 'staff:write',
      'settings:read', 'settings:write',
      'audit:read',
      'mtn:test',
    ],
    active: true,
    phone: '+250 788 123 456',
    lastLoginAt: '2026-09-27T16:45:00.000Z',
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'staff-2',
    name: 'Jean-Paul Habimana',
    email: 'orders@furnitura.luxury',
    role: 'ORDER_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    permissions: ['orders:read', 'orders:write', 'customers:read', 'delivery:read', 'delivery:write', 'notifications:read'],
    active: true,
    phone: '+250 788 234 567',
    lastLoginAt: '2026-09-27T15:20:00.000Z',
    createdAt: '2026-02-15T09:00:00.000Z',
  },
  {
    id: 'staff-3',
    name: 'Aline Mukamana',
    email: 'finance@furnitura.luxury',
    role: 'FINANCE_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    permissions: ['payments:read', 'payments:write', 'orders:read', 'discounts:read', 'discounts:write', 'analytics:read', 'mtn:test', 'audit:read'],
    active: true,
    phone: '+250 788 345 678',
    lastLoginAt: '2026-09-27T14:10:00.000Z',
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'staff-4',
    name: 'Eric Ndayisaba',
    email: 'catalog@furnitura.luxury',
    role: 'PRODUCT_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    permissions: ['products:read', 'products:write', 'inventory:read', 'inventory:write', 'categories:read', 'categories:write', '3d:read', '3d:write', 'reviews:read', 'reviews:write'],
    active: true,
    phone: '+250 788 456 789',
    lastLoginAt: '2026-09-26T17:30:00.000Z',
    createdAt: '2026-03-10T11:00:00.000Z',
  },
  {
    id: 'staff-5',
    name: 'Clarisse Keza',
    email: 'content@furnitura.luxury',
    role: 'CONTENT_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    permissions: ['cms:read', 'cms:write', 'products:read', 'reviews:read', 'reviews:write', '3d:read'],
    active: true,
    phone: '+250 788 567 890',
    lastLoginAt: '2026-09-25T11:45:00.000Z',
    createdAt: '2026-04-01T08:30:00.000Z',
  },
  {
    id: 'staff-6',
    name: 'David Karekezi',
    email: 'support@furnitura.luxury',
    role: 'SUPPORT_AGENT',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    permissions: ['orders:read', 'customers:read', 'customers:write', 'reviews:read', 'reviews:write', 'notifications:read'],
    active: true,
    phone: '+250 788 678 901',
    lastLoginAt: '2026-09-27T16:00:00.000Z',
    createdAt: '2026-05-15T12:00:00.000Z',
  },
];

// Seed Reviews
const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    productId: 'prod-7',
    productName: 'Modular Velvet Sectional Sofa',
    productImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    customerName: 'Claire Mutoni',
    customerEmail: 'claire.mutoni@kigaliluxury.rw',
    rating: 5,
    title: 'Transformed our main living salon completely',
    comment: 'The plum velvet is breathtaking in person. The deep seats and modular comfort exceeded our expectations. Delivery and setup in Nyarutarama was flawless!',
    date: '2026-09-26T14:30:00.000Z',
    status: 'APPROVED',
    verifiedBuyer: true,
    reply: {
      author: 'FURNITURA Concierge',
      text: 'Thank you Claire! We are delighted the Modular Velvet Sectional brings such elegance to your salon.',
      date: '2026-09-26T16:00:00.000Z',
    },
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    productName: 'Sapphire Velvet Accent Chair',
    productImage: '/hero-chair.jpg',
    customerName: 'Patrick Gakwaya',
    customerEmail: 'patrick.gakwaya@gmail.com',
    rating: 5,
    title: 'Solid craftsmanship & stunning gold base',
    comment: 'Ordered two chairs for our executive office reception. The 3D preview was totally accurate to the real materials.',
    date: '2026-09-25T10:15:00.000Z',
    status: 'APPROVED',
    verifiedBuyer: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    productName: 'Upholstered Bed Frame',
    productImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    customerName: 'Sandrine Uwamahoro',
    customerEmail: 'sandrine.u@yahoo.fr',
    rating: 5,
    title: 'Whisper quiet and heavenly headboard cushion',
    comment: 'The acoustic slat rails are real—zero squeaks. Beautiful linen texture.',
    date: '2026-09-24T18:20:00.000Z',
    status: 'APPROVED',
    verifiedBuyer: true,
  },
  {
    id: 'rev-4',
    productId: 'prod-8',
    productName: 'Sculptural Round Dining Set',
    productImage: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
    customerName: 'Emmanuel Gasana',
    customerEmail: 'e.gasana@techrwanda.com',
    rating: 5,
    title: 'Stain resistant coating saved dinner party',
    comment: 'Red wine spill wiped right off the walnut top without leaving any mark. Highly recommend.',
    date: '2026-09-22T20:05:00.000Z',
    status: 'APPROVED',
    verifiedBuyer: true,
  },
  {
    id: 'rev-5',
    productId: 'prod-5',
    productName: 'Ergonomic Office Chair',
    productImage: 'https://images.unsplash.com/photo-1580481077197-285b0cb046b4?auto=format&fit=crop&w=800&q=80',
    customerName: 'Yvette Ingabire',
    customerEmail: 'yvette.ingabire@outlook.com',
    rating: 4,
    title: 'Excellent lumbar support',
    comment: 'Very comfortable for long remote work sessions. Assembly took about 15 minutes.',
    date: '2026-09-20T11:30:00.000Z',
    status: 'PENDING',
    verifiedBuyer: true,
  },
];

// Seed Real Orders with strict status transitions
const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: 'FURN-2026-000101',
    orderNumber: 'FURN-2026-000101',
    items: [
      {
        productId: 'prod-7',
        name: 'Modular Velvet Sectional Sofa',
        sku: 'FUR-LIV-007',
        price: 1499,
        originalPrice: 1799,
        quantity: 1,
        colorName: 'Signature Plum',
        image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
        discountAmount: 150,
        subtotal: 1349,
      },
      {
        productId: 'prod-2',
        name: 'Modern Coffee Table',
        sku: 'FUR-LIV-002',
        price: 199,
        originalPrice: 229,
        quantity: 1,
        colorName: 'Smoked Walnut',
        image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=800&q=80',
        discountAmount: 20,
        subtotal: 179,
      },
    ],
    subtotal: 1698,
    discountAmount: 170,
    couponCode: 'FURNITURA10',
    shippingFee: 0,
    whiteGloveFee: 40,
    total: 1568,
    currency: 'USD',
    customer: {
      fullName: 'Hon. Jean-Luc Nkurunziza',
      email: 'jl.nkurunziza@primature.gov.rw',
      phone: '+250 788 554 433',
      province: 'Kigali City',
      district: 'Gasabo',
      sector: 'Kacyiru',
      address: 'Villa 14, KG 9 Avenue, Kacyiru, Kigali',
      notes: 'Please call security gate 15 minutes before arrival. White glove assembly required in upper reception lounge.',
    },
    deliveryZoneId: 'zone-kigali-urban',
    deliveryZoneName: 'Kigali Urban Express',
    orderStatus: 'DELIVERED',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'SUCCESSFUL',
    paymentReferenceId: 'b7c3d190-7f22-491a-b108-e8a719910001',
    paymentId: 'PAY-MTN-1001',
    financialTransactionId: 'MTN-RW-9948201',
    timeline: [
      { id: 't-1', timestamp: '2026-09-24T09:12:00.000Z', actor: 'System', event: 'Order created via Online Checkout', status: 'PENDING_PAYMENT' },
      { id: 't-2', timestamp: '2026-09-24T09:14:22.000Z', actor: 'MTN MoMo Gateway', event: 'Payment verified and confirmed ($1,568.00)', status: 'PAID' },
      { id: 't-3', timestamp: '2026-09-24T10:30:00.000Z', actor: 'Jean-Paul Habimana', event: 'Order verified & sent to Kigali logistics depot', status: 'PROCESSING' },
      { id: 't-4', timestamp: '2026-09-25T08:00:00.000Z', actor: 'Logistics Team', event: 'Packed with velvet preservation wrapping & brass protectors', status: 'READY_FOR_DELIVERY' },
      { id: 't-5', timestamp: '2026-09-25T11:00:00.000Z', actor: 'Courier Dispatch', event: 'Out for white-glove delivery on Van #04', status: 'OUT_FOR_DELIVERY' },
      { id: 't-6', timestamp: '2026-09-25T14:45:00.000Z', actor: 'Driver (Samuel)', event: 'Delivered and assembled in client reception. Customer signed bill of lading.', status: 'DELIVERED' },
    ],
    staffNotes: 'VIP diplomatic client. Delivered on time and received stellar verbal compliment.',
    createdAt: '2026-09-24T09:12:00.000Z',
    updatedAt: '2026-09-25T14:45:00.000Z',
  },
  {
    id: 'FURN-2026-000102',
    orderNumber: 'FURN-2026-000102',
    items: [
      {
        productId: 'prod-3',
        name: 'Upholstered Bed Frame',
        sku: 'FUR-BED-003',
        price: 699,
        originalPrice: 799,
        quantity: 1,
        colorName: 'Imperial Violet',
        image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
        discountAmount: 140,
        subtotal: 559,
      },
      {
        productId: 'prod-11',
        name: 'Velvet Ottoman Pouf',
        sku: 'FUR-LIV-011',
        price: 135,
        originalPrice: 150,
        quantity: 2,
        colorName: 'Plum Violet',
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
        discountAmount: 54,
        subtotal: 216,
      },
    ],
    subtotal: 969,
    discountAmount: 194,
    couponCode: 'LUXURY20',
    shippingFee: 0,
    whiteGloveFee: 0,
    total: 775,
    currency: 'USD',
    customer: {
      fullName: 'Dr. Antoinette Mukarubega',
      email: 'a.mukarubega@kingfaisalhospital.rw',
      phone: '+250 788 776 554',
      province: 'Kigali City',
      district: 'Gasabo',
      sector: 'Kibagabaga',
      address: 'KG 19 Ave, Plot 88, Kibagabaga Hill',
      notes: 'Delivery between 4 PM and 7 PM preferred after clinic hours.',
    },
    deliveryZoneId: 'zone-kigali-urban',
    deliveryZoneName: 'Kigali Urban Express',
    orderStatus: 'OUT_FOR_DELIVERY',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'SUCCESSFUL',
    paymentReferenceId: 'c8d4e2a1-8033-5a2b-c219-f9b820020002',
    paymentId: 'PAY-MTN-1002',
    financialTransactionId: 'MTN-RW-9948832',
    timeline: [
      { id: 't-1', timestamp: '2026-09-26T15:20:00.000Z', actor: 'System', event: 'Order created via Online Checkout', status: 'PENDING_PAYMENT' },
      { id: 't-2', timestamp: '2026-09-26T15:21:40.000Z', actor: 'MTN MoMo Gateway', event: 'Payment confirmed ($775.00)', status: 'PAID' },
      { id: 't-3', timestamp: '2026-09-27T08:30:00.000Z', actor: 'Jean-Paul Habimana', event: 'Order processed and assigned to delivery queue', status: 'PROCESSING' },
      { id: 't-4', timestamp: '2026-09-27T11:00:00.000Z', actor: 'Logistics Depot', event: 'Inspected and loaded onto dispatch truck', status: 'READY_FOR_DELIVERY' },
      { id: 't-5', timestamp: '2026-09-27T14:00:00.000Z', actor: 'Driver (Alexis)', event: 'En route to Kibagabaga Hill', status: 'OUT_FOR_DELIVERY' },
    ],
    createdAt: '2026-09-26T15:20:00.000Z',
    updatedAt: '2026-09-27T14:00:00.000Z',
  },
  {
    id: 'FURN-2026-000103',
    orderNumber: 'FURN-2026-000103',
    items: [
      {
        productId: 'prod-8',
        name: 'Sculptural Round Dining Set',
        sku: 'FUR-DIN-008',
        price: 899,
        originalPrice: 1199,
        quantity: 1,
        colorName: 'Dark Plum & Walnut',
        image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
        discountAmount: 0,
        subtotal: 899,
      },
    ],
    subtotal: 899,
    discountAmount: 0,
    shippingFee: 0,
    whiteGloveFee: 65,
    total: 964,
    currency: 'USD',
    customer: {
      fullName: 'Marc Cyubahiro',
      email: 'mcyubahiro@lakekivuresort.com',
      phone: '+250 788 998 877',
      province: 'Western Province',
      district: 'Rubavu',
      sector: 'Gisenyi',
      address: 'Kivu Serena Road, Palm Beach Residences #3',
      notes: 'Direct delivery to dining terrace overlooking Lake Kivu.',
    },
    deliveryZoneId: 'zone-western',
    deliveryZoneName: 'Western Province (Rubavu & Karongi)',
    orderStatus: 'PROCESSING',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'SUCCESSFUL',
    paymentReferenceId: 'd9e5f3b2-9144-6b3c-d320-0ac931130003',
    paymentId: 'PAY-MTN-1003',
    financialTransactionId: 'MTN-RW-9949104',
    timeline: [
      { id: 't-1', timestamp: '2026-09-27T10:15:00.000Z', actor: 'System', event: 'Order created', status: 'PENDING_PAYMENT' },
      { id: 't-2', timestamp: '2026-09-27T10:17:05.000Z', actor: 'MTN MoMo Gateway', event: 'Payment confirmed via MoMo Push ($964.00)', status: 'PAID' },
      { id: 't-3', timestamp: '2026-09-27T11:45:00.000Z', actor: 'Diane Uwase', event: 'Approved for Gisenyi weekly long-haul freight shuttle', status: 'PROCESSING' },
    ],
    createdAt: '2026-09-27T10:15:00.000Z',
    updatedAt: '2026-09-27T11:45:00.000Z',
  },
  {
    id: 'FURN-2026-000104',
    orderNumber: 'FURN-2026-000104',
    items: [
      {
        productId: 'prod-5',
        name: 'Ergonomic Office Chair',
        sku: 'FUR-OFF-005',
        price: 249,
        originalPrice: 289,
        quantity: 2,
        colorName: 'Executive Slate',
        image: 'https://images.unsplash.com/photo-1580481077197-285b0cb046b4?auto=format&fit=crop&w=800&q=80',
        discountAmount: 50,
        subtotal: 448,
      },
      {
        productId: 'prod-6',
        name: 'Writing Desk',
        sku: 'FUR-OFF-006',
        price: 254,
        originalPrice: 299,
        quantity: 1,
        colorName: 'Natural Oak',
        image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
        discountAmount: 25,
        subtotal: 229,
      },
    ],
    subtotal: 752,
    discountAmount: 75,
    couponCode: 'FURNITURA10',
    shippingFee: 25,
    total: 702,
    currency: 'USD',
    customer: {
      fullName: 'Belise Umutoni',
      email: 'belise.u@innovaterwanda.io',
      phone: '+250 788 443 322',
      province: 'Kigali City',
      district: 'Nyarugenge',
      sector: 'Kiyovu',
      address: 'Kiyovu Green Hills, KN 43 St, House 12',
    },
    deliveryZoneId: 'zone-kigali-urban',
    deliveryZoneName: 'Kigali Urban Express',
    orderStatus: 'PENDING_PAYMENT',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'PENDING',
    paymentReferenceId: 'e0f6a4c3-0255-7c4d-e431-1bd042240004',
    paymentId: 'PAY-MTN-1004',
    timeline: [
      { id: 't-1', timestamp: '2026-09-27T16:30:00.000Z', actor: 'System', event: 'Checkout initiated, MTN RequestToPay sent to +250 788 443 322', status: 'PENDING_PAYMENT' },
    ],
    createdAt: '2026-09-27T16:30:00.000Z',
    updatedAt: '2026-09-27T16:30:00.000Z',
  },
  {
    id: 'FURN-2026-000105',
    orderNumber: 'FURN-2026-000105',
    items: [
      {
        productId: 'prod-4',
        name: 'Wooden Sideboard',
        sku: 'FUR-STO-004',
        price: 399,
        originalPrice: 499,
        quantity: 1,
        colorName: 'Natural Ash',
        image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80',
        discountAmount: 0,
        subtotal: 399,
      },
    ],
    subtotal: 399,
    discountAmount: 0,
    shippingFee: 25,
    total: 424,
    currency: 'USD',
    customer: {
      fullName: 'Christian Mugisha',
      email: 'c.mugisha@gmail.com',
      phone: '+250 788 110 000',
      province: 'Kigali City',
      district: 'Kicukiro',
      sector: 'Gikondo',
      address: 'KK 15 Rd, Gikondo Industrial Park Gate',
    },
    deliveryZoneId: 'zone-kigali-urban',
    deliveryZoneName: 'Kigali Urban Express',
    orderStatus: 'PENDING_PAYMENT',
    paymentMethod: 'MTN_MOMO',
    paymentStatus: 'FAILED',
    paymentReferenceId: 'f1a7b5d4-1366-8d5e-f542-2ce153350005',
    paymentId: 'PAY-MTN-1005',
    timeline: [
      { id: 't-1', timestamp: '2026-09-27T15:00:00.000Z', actor: 'System', event: 'Order initiated', status: 'PENDING_PAYMENT' },
      { id: 't-2', timestamp: '2026-09-27T15:02:15.000Z', actor: 'MTN Gateway', event: 'Payment failed (Insufficient balance)', status: 'PENDING_PAYMENT' },
    ],
    staffNotes: 'Payment declined by MTN. Customer contacted via SMS to retry with alternate account.',
    createdAt: '2026-09-27T15:00:00.000Z',
    updatedAt: '2026-09-27T15:02:15.000Z',
  },
];

// Seed Payments Store
const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    paymentId: 'PAY-MTN-1001',
    orderId: 'FURN-2026-000101',
    externalId: 'FURN-2026-000101',
    mtnReferenceId: 'b7c3d190-7f22-491a-b108-e8a719910001',
    amount: 1568,
    currency: 'EUR',
    phoneNumberMasked: '+250 788 *** 433',
    rawPhoneNumber: '250788554433',
    provider: 'MTN_MOMO',
    status: 'SUCCESSFUL',
    createdAt: '2026-09-24T09:12:00.000Z',
    updatedAt: '2026-09-24T09:14:22.000Z',
    itemsSummary: '1x Modular Velvet Sectional Sofa, 1x Modern Coffee Table',
    payerMessage: 'FURNITURA Order FURN-2026-000101',
    financialTransactionId: 'MTN-RW-9948201',
  },
  {
    paymentId: 'PAY-MTN-1002',
    orderId: 'FURN-2026-000102',
    externalId: 'FURN-2026-000102',
    mtnReferenceId: 'c8d4e2a1-8033-5a2b-c219-f9b820020002',
    amount: 775,
    currency: 'EUR',
    phoneNumberMasked: '+250 788 *** 554',
    rawPhoneNumber: '250788776554',
    provider: 'MTN_MOMO',
    status: 'SUCCESSFUL',
    createdAt: '2026-09-26T15:20:00.000Z',
    updatedAt: '2026-09-26T15:21:40.000Z',
    itemsSummary: '1x Upholstered Bed Frame, 2x Velvet Ottoman Pouf',
    payerMessage: 'FURNITURA Order FURN-2026-000102',
    financialTransactionId: 'MTN-RW-9948832',
  },
  {
    paymentId: 'PAY-MTN-1003',
    orderId: 'FURN-2026-000103',
    externalId: 'FURN-2026-000103',
    mtnReferenceId: 'd9e5f3b2-9144-6b3c-d320-0ac931130003',
    amount: 964,
    currency: 'EUR',
    phoneNumberMasked: '+250 788 *** 877',
    rawPhoneNumber: '250788998877',
    provider: 'MTN_MOMO',
    status: 'SUCCESSFUL',
    createdAt: '2026-09-27T10:15:00.000Z',
    updatedAt: '2026-09-27T10:17:05.000Z',
    itemsSummary: '1x Sculptural Round Dining Set',
    payerMessage: 'FURNITURA Order FURN-2026-000103',
    financialTransactionId: 'MTN-RW-9949104',
  },
  {
    paymentId: 'PAY-MTN-1004',
    orderId: 'FURN-2026-000104',
    externalId: 'FURN-2026-000104',
    mtnReferenceId: 'e0f6a4c3-0255-7c4d-e431-1bd042240004',
    amount: 702,
    currency: 'EUR',
    phoneNumberMasked: '+250 788 *** 322',
    rawPhoneNumber: '250788443322',
    provider: 'MTN_MOMO',
    status: 'PENDING',
    createdAt: '2026-09-27T16:30:00.000Z',
    updatedAt: '2026-09-27T16:30:00.000Z',
    itemsSummary: '2x Ergonomic Office Chair, 1x Writing Desk',
    payerMessage: 'FURNITURA Order FURN-2026-000104',
  },
  {
    paymentId: 'PAY-MTN-1005',
    orderId: 'FURN-2026-000105',
    externalId: 'FURN-2026-000105',
    mtnReferenceId: 'f1a7b5d4-1366-8d5e-f542-2ce153350005',
    amount: 424,
    currency: 'EUR',
    phoneNumberMasked: '+250 788 *** 000',
    rawPhoneNumber: '250788110000',
    provider: 'MTN_MOMO',
    status: 'FAILED',
    failureReason: 'Insufficient funds or account inactive',
    createdAt: '2026-09-27T15:00:00.000Z',
    updatedAt: '2026-09-27T15:02:15.000Z',
    itemsSummary: '1x Wooden Sideboard',
    payerMessage: 'FURNITURA Order FURN-2026-000105',
  },
];

// Seed Customers
const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cust-1',
    fullName: 'Hon. Jean-Luc Nkurunziza',
    email: 'jl.nkurunziza@primature.gov.rw',
    phone: '+250 788 554 433',
    province: 'Kigali City',
    district: 'Gasabo',
    sector: 'Kacyiru',
    address: 'Villa 14, KG 9 Avenue, Kacyiru, Kigali',
    notes: 'VIP Client. Enjoys royal velvet fabrics and bespoke dining sets. Requires white glove installation.',
    tags: ['VIP', 'Government', 'High Value'],
    totalOrders: 3,
    totalSpent: 4890,
    lastOrderDate: '2026-09-24T09:12:00.000Z',
    status: 'VIP',
    createdAt: '2026-02-10T11:00:00.000Z',
  },
  {
    id: 'cust-2',
    fullName: 'Dr. Antoinette Mukarubega',
    email: 'a.mukarubega@kingfaisalhospital.rw',
    phone: '+250 788 776 554',
    province: 'Kigali City',
    district: 'Gasabo',
    sector: 'Kibagabaga',
    address: 'KG 19 Ave, Plot 88, Kibagabaga Hill',
    notes: 'Surgeon at King Faisal Hospital. Regular luxury bedroom customer.',
    tags: ['Medical', 'Repeat Buyer', 'Verified'],
    totalOrders: 2,
    totalSpent: 1980,
    lastOrderDate: '2026-09-26T15:20:00.000Z',
    status: 'ACTIVE',
    createdAt: '2026-04-12T14:30:00.000Z',
  },
  {
    id: 'cust-3',
    fullName: 'Marc Cyubahiro',
    email: 'mcyubahiro@lakekivuresort.com',
    phone: '+250 788 998 877',
    province: 'Western Province',
    district: 'Rubavu',
    sector: 'Gisenyi',
    address: 'Kivu Serena Road, Palm Beach Residences #3',
    notes: 'Resort owner in Rubavu. Orders contract and outdoor furniture collections.',
    tags: ['Hospitality', 'Commercial', 'Western Province'],
    totalOrders: 4,
    totalSpent: 7200,
    lastOrderDate: '2026-09-27T10:15:00.000Z',
    status: 'VIP',
    createdAt: '2026-01-18T09:15:00.000Z',
  },
  {
    id: 'cust-4',
    fullName: 'Belise Umutoni',
    email: 'belise.u@innovaterwanda.io',
    phone: '+250 788 443 322',
    province: 'Kigali City',
    district: 'Nyarugenge',
    sector: 'Kiyovu',
    address: 'Kiyovu Green Hills, KN 43 St, House 12',
    notes: 'Tech entrepreneur. Furnishing new private home office in Kiyovu.',
    tags: ['Tech', 'Office', 'Kiyovu'],
    totalOrders: 1,
    totalSpent: 702,
    lastOrderDate: '2026-09-27T16:30:00.000Z',
    status: 'ACTIVE',
    createdAt: '2026-09-27T16:25:00.000Z',
  },
  {
    id: 'cust-5',
    fullName: 'Christian Mugisha',
    email: 'c.mugisha@gmail.com',
    phone: '+250 788 110 000',
    province: 'Kigali City',
    district: 'Kicukiro',
    sector: 'Gikondo',
    address: 'KK 15 Rd, Gikondo Industrial Park Gate',
    notes: 'Recent customer, attempted payment declined. Followed up by customer support.',
    tags: ['Follow Up Needed'],
    totalOrders: 1,
    totalSpent: 0,
    lastOrderDate: '2026-09-27T15:00:00.000Z',
    status: 'ACTIVE',
    createdAt: '2026-09-27T14:50:00.000Z',
  },
];

// Seed Inventory Logs
const INITIAL_INVENTORY_LOGS: InventoryLogItem[] = [
  {
    id: 'inv-1',
    productId: 'prod-7',
    productName: 'Modular Velvet Sectional Sofa',
    sku: 'FUR-LIV-007',
    adjustmentType: 'SALE',
    quantityChange: -1,
    previousStock: 8,
    newStock: 7,
    reason: 'Customer purchase for Order FURN-2026-000101',
    actor: 'System (Checkout)',
    timestamp: '2026-09-24T09:12:00.000Z',
  },
  {
    id: 'inv-2',
    productId: 'prod-1',
    productName: 'Sapphire Velvet Accent Chair',
    sku: 'FUR-LIV-001',
    adjustmentType: 'RESTOCK',
    quantityChange: 10,
    previousStock: 4,
    newStock: 14,
    reason: 'Imported container from Milan Italian Atelier received & inspected',
    actor: 'Eric Ndayisaba (Product Mgr)',
    timestamp: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'inv-3',
    productId: 'prod-3',
    productName: 'Upholstered Bed Frame',
    sku: 'FUR-BED-003',
    adjustmentType: 'SALE',
    quantityChange: -1,
    previousStock: 9,
    newStock: 8,
    reason: 'Customer purchase for Order FURN-2026-000102',
    actor: 'System (Checkout)',
    timestamp: '2026-09-26T15:20:00.000Z',
  },
  {
    id: 'inv-4',
    productId: 'prod-12',
    productName: 'Teak Outdoor Lounge Set',
    sku: 'FUR-OUT-012',
    adjustmentType: 'MANUAL_ADJUSTMENT',
    quantityChange: -1,
    previousStock: 7,
    newStock: 6,
    reason: 'Allocated to Kigali Flagship Showroom display window',
    actor: 'Diane Uwase (Super Admin)',
    timestamp: '2026-09-22T14:30:00.000Z',
  },
];

// Seed Audit Logs
const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: '2026-09-27T16:45:10.000Z',
    actorId: 'staff-1',
    actorName: 'Diane Uwase',
    actorRole: 'SUPER_ADMIN',
    action: 'LOGIN',
    resource: 'AUTH',
    details: 'Super Admin successfully logged into FURNITURA Operations Portal',
    ipAddress: '197.243.22.84 (Kigali, RW)',
  },
  {
    id: 'audit-2',
    timestamp: '2026-09-27T15:22:00.000Z',
    actorId: 'staff-2',
    actorName: 'Jean-Paul Habimana',
    actorRole: 'ORDER_MANAGER',
    action: 'ORDER_STATUS_UPDATE',
    resource: 'ORDERS',
    resourceId: 'FURN-2026-000102',
    details: 'Changed order status from READY_FOR_DELIVERY to OUT_FOR_DELIVERY',
    beforeState: { status: 'READY_FOR_DELIVERY' },
    afterState: { status: 'OUT_FOR_DELIVERY' },
    ipAddress: '197.243.22.84',
  },
  {
    id: 'audit-3',
    timestamp: '2026-09-27T11:45:00.000Z',
    actorId: 'staff-1',
    actorName: 'Diane Uwase',
    actorRole: 'SUPER_ADMIN',
    action: 'ORDER_STATUS_UPDATE',
    resource: 'ORDERS',
    resourceId: 'FURN-2026-000103',
    details: 'Approved order and advanced status to PROCESSING',
    beforeState: { status: 'PAID' },
    afterState: { status: 'PROCESSING' },
    ipAddress: '197.243.22.84',
  },
  {
    id: 'audit-4',
    timestamp: '2026-09-26T16:00:00.000Z',
    actorId: 'staff-5',
    actorName: 'Clarisse Keza',
    actorRole: 'CONTENT_MANAGER',
    action: 'REVIEW_REPLY',
    resource: 'REVIEWS',
    resourceId: 'rev-1',
    details: 'Published official concierge reply to verified buyer Claire Mutoni',
    ipAddress: '197.243.22.84',
  },
  {
    id: 'audit-5',
    timestamp: '2026-09-25T14:45:00.000Z',
    actorId: 'staff-2',
    actorName: 'Jean-Paul Habimana',
    actorRole: 'ORDER_MANAGER',
    action: 'ORDER_STATUS_UPDATE',
    resource: 'ORDERS',
    resourceId: 'FURN-2026-000101',
    details: 'Marked order as DELIVERED after receipt confirmation',
    beforeState: { status: 'OUT_FOR_DELIVERY' },
    afterState: { status: 'DELIVERED' },
    ipAddress: '197.243.22.84',
  },
  {
    id: 'audit-6',
    timestamp: '2026-09-20T10:00:00.000Z',
    actorId: 'staff-4',
    actorName: 'Eric Ndayisaba',
    actorRole: 'PRODUCT_MANAGER',
    action: 'INVENTORY_RESTOCK',
    resource: 'INVENTORY',
    resourceId: 'prod-1',
    details: 'Restocked Sapphire Velvet Accent Chair by +10 units (New stock: 14)',
    beforeState: { stockCount: 4 },
    afterState: { stockCount: 14 },
    ipAddress: '197.243.22.84',
  },
];

// Seed Notifications
const INITIAL_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-1',
    title: 'New MTN MoMo Payment Received',
    message: 'Payment of $964.00 confirmed for Order #FURN-2026-000103 by Marc Cyubahiro.',
    type: 'payment',
    severity: 'success',
    link: '/admin/orders/FURN-2026-000103',
    isRead: false,
    isArchived: false,
    createdAt: '2026-09-27T10:17:05.000Z',
  },
  {
    id: 'notif-2',
    title: 'Payment Pending Authorization',
    message: 'Order #FURN-2026-000104 ($702.00) waiting for MTN MoMo PIN approval on +250 788 443 322.',
    type: 'order',
    severity: 'info',
    link: '/admin/orders/FURN-2026-000104',
    isRead: false,
    isArchived: false,
    createdAt: '2026-09-27T16:30:00.000Z',
  },
  {
    id: 'notif-3',
    title: 'Low Stock Alert: Teak Outdoor Set',
    message: 'Only 6 units remaining for "Teak Outdoor Lounge Set" (SKU: FUR-OUT-012).',
    type: 'inventory',
    severity: 'warning',
    link: '/admin/inventory',
    isRead: false,
    isArchived: false,
    createdAt: '2026-09-27T08:00:00.000Z',
  },
  {
    id: 'notif-4',
    title: 'Payment Failed: Order #FURN-2026-000105',
    message: 'MTN Gateway returned "Insufficient funds" for customer Christian Mugisha ($424.00).',
    type: 'payment',
    severity: 'error',
    link: '/admin/payments/PAY-MTN-1005',
    isRead: false,
    isArchived: false,
    createdAt: '2026-09-27T15:02:15.000Z',
  },
  {
    id: 'notif-5',
    title: 'New 5-Star Review Published',
    message: 'Claire Mutoni posted a 5-star review on "Modular Velvet Sectional Sofa".',
    type: 'review',
    severity: 'success',
    link: '/admin/reviews',
    isRead: true,
    isArchived: false,
    createdAt: '2026-09-26T14:30:00.000Z',
  },
];

// Seed CMS
const INITIAL_CMS: CMSConfig = {
  heroTitle: 'Sculptural Luxury Living',
  heroSubtitle: 'Elevate your space with bespoke craftsmanship, plush royal velvets, and precision 3D-engineered contours.',
  heroBadge: '2026 COUTURE LIVING COLLECTION',
  heroPrimaryCtaText: 'EXPLORE CATALOG',
  heroSecondaryCtaText: 'LAUNCH 3D STUDIO',
  announcementText: '✨ FREE WHITE-GLOVE VIP DELIVERY ON ORDERS OVER $500 • MTN MOMO SANDBOX GATEWAY ACTIVE',
  announcementActive: true,
  dealOfTheWeekProductId: 'prod-8',
  dealCountdownEndDate: '2026-10-05T23:59:59.000Z',
  featuredProductIds: ['prod-7', 'prod-1', 'prod-3', 'prod-8'],
  promoBanners: [
    {
      id: 'promo-1',
      tag: 'NEW COLLECTION',
      title: 'Modern Sofas For Your Home',
      subtitle: 'Comfort that complements your style.',
      image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
      buttonText: 'SHOP NOW',
      roomFilter: 'living',
      active: true,
    },
    {
      id: 'promo-2',
      tag: 'BEST SELLERS',
      title: 'Stylish Dining Furniture',
      subtitle: 'Make every meal special.',
      image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
      buttonText: 'SHOP NOW',
      roomFilter: 'dining',
      active: true,
    },
    {
      id: 'promo-3',
      tag: 'LIMITED OFFER',
      title: 'Up To 30% Off On Bedroom Sets',
      subtitle: 'Premium quality. Smart designs.',
      image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
      buttonText: 'SHOP NOW',
      roomFilter: 'bedroom',
      discountText: '30% OFF',
      active: true,
    },
  ],
};

// Seed Settings
const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'FURNITURA Luxury Commerce',
  legalEntityName: 'FURNITURA Rwanda Ltd.',
  supportEmail: 'concierge@furnitura.luxury',
  supportPhone: '+250 788 123 456',
  storeAddress: 'Boulevard de la Révolution, Kigali Heights Suite 402, Kigali, Rwanda',
  currency: 'USD',
  currencySymbol: '$',
  taxRatePercent: 0,
  freeShippingThreshold: 500,
  standardShippingFee: 25,
  whiteGloveFee: 40,
  inventoryLowStockThreshold: 10,
  orderPrefix: 'FURN-2026',
  environment: 'sandbox',
  maintenanceMode: false,
  allowGuestCheckout: true,
  requirePhoneVerification: false,
};

// In-Memory Database Class
class MemoryDatabase {
  products: Map<string, Product> = new Map();
  categories: Map<string, CategoryItem> = new Map();
  discounts: Map<string, DiscountRule> = new Map();
  deliveryZones: Map<string, DeliveryZone> = new Map();
  staff: Map<string, StaffUser> = new Map();
  orders: Map<string, AdminOrder> = new Map();
  payments: Map<string, PaymentRecord> = new Map();
  customers: Map<string, CustomerProfile> = new Map();
  reviews: Map<string, ReviewItem> = new Map();
  inventoryLogs: InventoryLogItem[] = [];
  auditLogs: AuditLog[] = [];
  notifications: AdminNotification[] = [];
  cms: CMSConfig = { ...INITIAL_CMS };
  settings: StoreSettings = { ...INITIAL_SETTINGS };

  constructor() {
    this.seed();
  }

  seed() {
    INITIAL_PRODUCTS.forEach((p) => this.products.set(p.id, { ...p }));
    INITIAL_CATEGORIES.forEach((c) => this.categories.set(c.id, { ...c }));
    INITIAL_DISCOUNTS.forEach((d) => this.discounts.set(d.id, { ...d }));
    INITIAL_DELIVERY_ZONES.forEach((z) => this.deliveryZones.set(z.id, { ...z }));
    INITIAL_STAFF.forEach((s) => this.staff.set(s.id, { ...s }));
    INITIAL_ORDERS.forEach((o) => this.orders.set(o.id, { ...o }));
    INITIAL_PAYMENTS.forEach((p) => this.payments.set(p.mtnReferenceId, { ...p }));
    INITIAL_CUSTOMERS.forEach((c) => this.customers.set(c.id, { ...c }));
    INITIAL_REVIEWS.forEach((r) => this.reviews.set(r.id, { ...r }));
    this.inventoryLogs = [...INITIAL_INVENTORY_LOGS];
    this.auditLogs = [...INITIAL_AUDIT_LOGS];
    this.notifications = [...INITIAL_NOTIFICATIONS];
  }

  // Audit Logger Helper
  logAudit(entry: {
    actorId?: string;
    actorName?: string;
    actorRole?: StaffRole;
    action: string;
    resource: string;
    resourceId?: string;
    details: string;
    beforeState?: any;
    afterState?: any;
    ipAddress?: string;
  }): AuditLog {
    const log: AuditLog = {
      id: `audit-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      timestamp: new Date().toISOString(),
      actorId: entry.actorId || 'staff-1',
      actorName: entry.actorName || 'Diane Uwase',
      actorRole: entry.actorRole || 'SUPER_ADMIN',
      action: entry.action,
      resource: entry.resource,
      resourceId: entry.resourceId,
      details: entry.details,
      beforeState: entry.beforeState,
      afterState: entry.afterState,
      ipAddress: entry.ipAddress || '197.243.22.84',
    };
    this.auditLogs.unshift(log);
    return log;
  }

  // Notification Helper
  addNotification(notif: {
    title: string;
    message: string;
    type: 'order' | 'payment' | 'inventory' | 'customer' | 'review' | 'system' | 'discount';
    severity?: 'info' | 'success' | 'warning' | 'error';
    link?: string;
  }): AdminNotification {
    const item: AdminNotification = {
      id: `notif-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      title: notif.title,
      message: notif.message,
      type: notif.type,
      severity: notif.severity || 'info',
      link: notif.link,
      isRead: false,
      isArchived: false,
      createdAt: new Date().toISOString(),
    };
    this.notifications.unshift(item);
    return item;
  }
}

export const db = new MemoryDatabase();
